### ISSUE TITLE
WordPress plugin main file parts

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/small-project#6]
- Prevent direct execution (ABSPATH)
- Prevent double activation (MY_FILE)
- Check requirement: PHP, core, multisite, plugin, library
  `wp => '5.1', php => '7.0', multisite => '5.1', plugins => ['wordpress-seo'], packages => ['psr/http']`
  https://github.com/wearerequired/wp-requirements-check/blob/master/WP_Requirements_Check.php
- Define constants, inspect their usage:
   - MY_FILE
   - MY_PATH
   - MY_SLUG
   - MY_URL
   - MY_VERSION
- Call register_activation_hook(), register_deactivation_hook(), register_uninstall_hook()
- Load autoloader
- Load translations
- Support WP-CLI
- ~~Run database migrations~~
- Bootstrap the plugin in `plugins_loaded`
- 💡 Anything else goes to its own file

**Comment by szepeviktor** [comment]
1. list of parts
1. order/dependency
1. structure

**Comment by szepeviktor** [comment]
Hello @cliffordp! This is a theoretical research on the main plugin parts: The Ultimate Main Plugin File.
Would you like to contribute?

**Comment by cliffordp** [comment]
Hi, @szepeviktor - I've not seen this repo before and am unsure what you're asking of me - but I don't know if I've ever needed a boilerplate for something temporary, and I'm curious about the use cases you've come across and how this might relate to WordPress.

**Comment by cliffordp** [comment]
OK, thanks for sharing. Feel free to reference https://github.com/cliffordp/cliff-wp-plugin-boilerplate as would be helpful to you.

**Comment by szepeviktor** [comment]
Done! 😄 

@cliffordp Could you take a look at the new main file and the classes in `src`?
I would be thankful for a code review.

**Comment by cliffordp** [comment]
Hi. I skimmed through. Here are some notes:

1. It's recommended to not use a closure (anon function) with hooks (action/filter) because then they cannot easily (if at all) be _un-hooked_
2. Personally, I find the global namespace `\` to clutter the code viewing but that's likely just what I'm used to - so no changes if you feel it important.
3. Code styling from WordPress, should you choose to adopt it (other than `array()`, which I prefer as its short form), would say to have more spacing, e.g. `\add_action('admin_notices', ..., 0, 0);` would be `\add_action( 'admin_notices', ..., 0, 0 );`
4. One big use of the Requirements class in an `if` is of course fine for running the code, but personally I'd want to see the Requirements class' result filterable via `apply_filters()`, passing the args used as one of the parameters. Just an idea.

Good luck going forward however you see fit. Keep up the good work :)

**Comment by szepeviktor** [comment]
Thank you for all four of your bullet points!

- backslashes will be gone with `use function ...;`
- WPCS is an anti-review laser gun :) no wonder PSR-12 exists, WPCS is for beginners and visually impaired people 👉 quote from https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#declaring-arrays
- filtering the results gives the user an unhealthy dose if liberty, making it pass with requirements unmet equals not checking anything at all, this code is not a plugin but a template

![kép](https://user-images.githubusercontent.com/952007/103084901-769e2a80-45e0-11eb-8104-3f16334aa35c.png)

I come from a decent embedded world where you flip one bit and the whole device goes to the bin!
